FROM oven/bun:latest AS build
WORKDIR /app

COPY package.json bun.lock ./
COPY packages ./packages
COPY apps ./apps

RUN bun install
RUN bun run --cwd apps/web prepare || true
RUN bun run --cwd apps/web build

EXPOSE 3000
CMD ["bun", "apps/web/build/index.js"]